# These are supported funding model platforms

github: abhint
# patreon: abhijithnt
# open_collective: # Replace with a single Open Collective username
# ko_fi: abhijithnt
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with a single Liberapay username
# issuehunt: AbhijithNT
# otechie: # Replace with a single Otechie username
# custom: ['paypal.me/abhijithnt']
